# Generated by Django 5.1.2 on 2024-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('short_caption', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
            ],
        ),
    ]
