# Generated by Django 5.1.2 on 2024-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(default='Нет описания'),
        ),
    ]
